### ISSUE TITLE
I tried to localize all the text, but some of them didn't work

### ISSUE THREAD

**Issue by anye77** [RandyKnapp/ValheimMods#291]
Localization.instance.Localize("$****");
This is my translation of Chinese
[https://github.com/anye77/ValheimMods](url)

**Comment by RandyKnapp** [comment]
Hello. The link is broken, I think because it's a private github. That's okay. 

It is not allowed for you to redistribute my code without permission. I understand that it is frustrating that Epic Loot is not fully localized yet. However, it would have been better if you had submitted a Pull Request to this repo instead.

**Comment by RandyKnapp** [comment]
你好。鏈接壞了，我想是因為它是一個私人的github。沒關係。

未經許可，您不得重新分發我的代碼。我知道 Epic Loot 尚未完全本地化令人沮喪。但是，如果您改為向此 repo 提交 Pull Request 會更好。

這是機器翻譯，希望能幫到你。

**Comment by anye77** [comment]
https://github.com/anye77/ValheimMods


Okay, I'll cancel the release

**Comment by RandyKnapp** [comment]
All text should be localized now in 331c2d2
