### ISSUE TITLE
Equipment and Quick Slots loading issue post Hearth and Home update.

### ISSUE THREAD

**Issue by agrosskurth** [RandyKnapp/ValheimMods#320]
Hey, I just wanted to make a note here that there is an issue with loading the Equipment and Quick Slots mod after the Hearth and Home update. I am not sure if you're aware of this yet, so I am making this issue. I can close it soon if you prefer or are already aware.

[Error  : Unity Log] ArgumentException: Undefined target method for patch method static bool EpicLoot.Console_Patch::Prefix(Console __instance)
Stack trace:
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <48ac0133328b486983afe98eee5b730e>:0)
Rethrow as HarmonyException: Patching exception in method null
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.Harmony.CreateAndPatchAll (System.Reflection.Assembly assembly, System.String harmonyInstanceId) (at <48ac0133328b486983afe98eee5b730e>:0)
EpicLoot.EpicLoot.Awake () (at <ea52786f3f914cba991542418b9f4805>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

[Info   :   BepInEx] Loading [Equipment and Quick Slots 2.0.12]
[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type Console and name InputText and parameters
[Error  : Unity Log] ArgumentException: Undefined target method for patch method static bool EquipmentAndQuickSlots.Console_Patch::Prefix(Console __instance)
Stack trace:
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <48ac0133328b486983afe98eee5b730e>:0)
Rethrow as HarmonyException: Patching exception in method null
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.Harmony.CreateAndPatchAll (System.Reflection.Assembly assembly, System.String harmonyInstanceId) (at <48ac0133328b486983afe98eee5b730e>:0)
EquipmentAndQuickSlots.EquipmentAndQuickSlots.Awake () (at <7357d835e275457d9f43a070d0c404de>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

**Comment by heather-reynolds** [comment]
Same error after Home and Hearth update.

**Comment by heather-reynolds** [comment]
https://github.com/RandyKnapp/ValheimMods/blob/3ba8c0578b96ad4e901079d052e49d0f5e45b7bc/EquipmentAndQuickSlots/Console_Patch.cs

**Comment by DerValiser** [comment]
Hey guys.  The first Error @agrosskurth mentioned, seems to be from EpicLoot. But of course I'm getting the same ones with the EquipmentAndQuickSlots.

The error itself is, because the Console-Class does not have an InputText Method any longer. I don't have a copy of the older Valheim.dll, which would be interesting.  Maybe this has been changed. But it's now the Terminal Class.  So this small change has solved the problem, but because I'm not 100% sure what I'm doing there, there are some other problems ;-)

Because I would like to play the game tomorrow, I had trouble to get my items back, due to this error.
I downloaded the code and managed to get it working in some way.  
I'm still getting endless errors during the game in the R2ModMan Log, BUT I was able to get my armor and the things from the quickslots. 

I can link you the changed EquipmentAndQuickSlots.dll   
It has the same Size and I ASSURE YOU that I have put any malware inside. 
But it's just in order to get your stuff back. Afterwards, you should disable this mod, until the Developer is able to fix it.

https://www.dropbox.com/s/tiy2hcmw8t2tcs5/EquipmentAndQuickSlots.dll?dl=0

**Comment by DerValiser** [comment]
PS: I know this is not the usual way to help at github. But my time is running out. I could have used the fix for my own, but I think you want your stuff back as well :)
If you read this, Randy. Sorry for that.  Just change Console to Terminal in your Console_Patch.  But there were some more trouble with Keycodes which does not exist any longer as string parameter.

**Comment by DerValiser** [comment]
Version 2.0.4 should work as well, according to the guys at Nexusmods. You could download it from there.

**Comment by tdierickx** [comment]
DerValiser, you're a godsend! I was tempted to just quit Valheim altogether. No way did I want to go all the way back to re-mining 120 iron to recraft all my iron tools, armor, upgrades, etc. THANK YOU!!

**Comment by DerValiser** [comment]
**BUGFIX UPDATE FOR HEART & HOME**
Yesterday I wrote a longer comment with a temporary Version which could be enabled just to get your stuff back. But you can ignore this posting now.

I rebuild the mod this morning again and now it seems that this mod is working again for longer use.
You can download a ZIP-File from my Dropbox just containing the EquipmentAndQuickSlots.dll.  You have to find this file on your PC on your own and overwrite it. I have not changed the Version number or anything else. Just fixed the Console-Bug and rebuild it in order to get it working.
Because I'm not using Nexusmods but R2ModMan, it would not be helpful for you to post my local path here.

[Download newer EquipmentAndQuickSlots.dll from my Dropbox](https://www.dropbox.com/s/ac1tr47cdrkq0vw/EquipmentAndQuickSlots.dll?dl=0)
﻿﻿
Have fun with the new Valheim Update.

PS: I'm not the original developer. I advice to update the mod  as soon as Randy has fixed it.

**Comment by 2077141408** [comment]
[Info   :   BepInEx] Loading [Equipment and Quick Slots 2.0.12]
[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type Console and name InputText and parameters
[Error  : Unity Log] ArgumentException: Undefined target method for patch method static bool EquipmentAndQuickSlots.Console_Patch::Prefix(Console __instance)
Stack trace:
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <48ac0133328b486983afe98eee5b730e>:0)
Rethrow as HarmonyException: Patching exception in method null
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.Harmony.CreateAndPatchAll (System.Reflection.Assembly assembly, System.String harmonyInstanceId) (at <48ac0133328b486983afe98eee5b730e>:0)
EquipmentAndQuickSlots.EquipmentAndQuickSlots.Awake () (at <fd21c93894b640aab1587118f571f348>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

**Comment by DerValiser** [comment]
@2077141408  Did you ever read something bevor in your life? Or do you just dump your shit into the internet?

**Comment by RandyKnapp** [comment]
Fixed in 2.0.14. @DerValiser you're not allowed to modify and redistribute my code. I'll be deleting your download links. Please take down your fix.

**Comment by DerValiser** [comment]
> 
> 
> Fixed in 2.0.14. @DerValiser you're not allowed to modify and redistribute my code. I'll be deleting your download links. Please take down your fix.

I have not distributed any sources. Better see to working off the PR before blaming others. And maybe provide correct license information.
