### ISSUE TITLE
Cooking Station can't remove food - Hearth & Home Update

### ISSUE THREAD

**Issue by shortybsd** [RandyKnapp/ValheimMods#321]
When you cook items on cooking station you are unable to remove them.

waiting patiently for an update much love in advance :)

**Comment by Dalayeth** [comment]
This is due to ExtendedItemDataFramework.

`[Error  : Unity Log] MissingFieldException: Field 'CookingStation.m_spawnOffset' not found.
Stack trace:
(wrapper dynamic-method) CookingStation.DMD<CookingStation::SpawnItem>(CookingStation,string,int,UnityEngine.Vector3)
CookingStation.RPC_RemoveDoneItem (System.Int64 sender, UnityEngine.Vector3 userPoint) (at <30933934adb94e3fa486522beec45894>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Delegate.DynamicInvokeImpl (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Delegate.DynamicInvoke (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
RoutedMethod`1[T].Invoke (System.Int64 rpc, ZPackage pkg) (at <30933934adb94e3fa486522beec45894>:0)
ZNetView.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData rpcData) (at <30933934adb94e3fa486522beec45894>:0)
ZRoutedRpc.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData data) (at <30933934adb94e3fa486522beec45894>:0)
ZRoutedRpc.InvokeRoutedRPC (System.Int64 targetPeerID, ZDOID targetZDO, System.String methodName, System.Object[] parameters) (at <30933934adb94e3fa486522beec45894>:0)
ZNetView.InvokeRPC (System.String method, System.Object[] parameters) (at <30933934adb94e3fa486522beec45894>:0)
CookingStation.OnInteract (Humanoid user) (at <30933934adb94e3fa486522beec45894>:0)
CookingStation.Interact (Humanoid user, System.Boolean hold, System.Boolean alt) (at <30933934adb94e3fa486522beec45894>:0)
Player.Interact (UnityEngine.GameObject go, System.Boolean hold, System.Boolean alt) (at <30933934adb94e3fa486522beec45894>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)`

**Comment by DerValiser** [comment]
Indeed, CookingStation does not have the property m_spawnOffset any longer. As long as I can see this in the valheim sourcecode.
I'm not able to test this, because the ExtendedItemDataFramework is not a mod on it's own, but it seems that other mods are using this. Maybe the EpicLoot. I have no idea. 

I'm just using MinimalStatusEffects which still runs fine and the EquipmentAndQuickSlots which I have fixed :)

You may try this DLL here and exchange it on your harddrive. I simply removed the Code for the CookingStation. Don't know exactly what the code was doing, but I think he just dropped the meat a bit further away as in the original game. So I don't think that this code is really required. And because it's buggy now it's better to remove it.

But MAYBE your other mod using this Library is working again.  Unfortunately I don't have the time to install other mods now and test this under all behaviours. But it might be worth a try.

https://www.dropbox.com/s/dwd4q4c4azpt5t0/ExtendedItemDataFramework.dll?dl=0

**Comment by shortybsd** [comment]
Indeed, ExtendedItemDataFramework is a dependency for EpicLoot. I posted here specifically for the ExtendedItemDataFramework issue. I should have been more specific :)
Thanks for your fix, I also saw your slots fix on another post. I will test them out here shortly!

**Comment by DerValiser** [comment]
As I just commented,  Epic Loot seems to have much more problem. But a lot of other mods are Using this Framework as well, as I see now. Maybe it helps, but in case of EpicLoot there would be further problems which randy should look at.

**Comment by Fuzzbling** [comment]
Happens for display stands as well, see posts here on Nexus:
https://www.nexusmods.com/valheim/mods/281?tab=posts

**Comment by RandyKnapp** [comment]
Fixed in 1.0.5
