### ISSUE TITLE
Epic Loot: Recalling randomly deletes item

### ISSUE THREAD

**Issue by JLewis1309** [RandyKnapp/ValheimMods#369]
Ive Found that sometimes while throwing an item with Recalling it will just delete the item instead of recalling it back into your inventory.
Ive had 2 nice legendary Iron Sledges just yeet themselves into oblivion for seemingly no reason.

**Comment by davidtaylornc** [comment]
If your thrown item passes outside the rendered world, it never lands and so cannot come back.  When scrap ZDOs are garbage collected the item gets deleted.  If your item lands in deep water, it stay on the bottom of the sea and does not come back.  The first case is not easily fixable sine the object scrapping algorithm is wholly unrelated to the throw code.  The second case seems to be the expected behavior given Valheim item pickup physics..
