### ISSUE TITLE
Error spam in BeepInEx

### ISSUE THREAD

**Issue by xilenasu** [RandyKnapp/ValheimMods#410]
Whenever I die, my BeepInEx is bombarded with an error (see below).
I play with 2 friends. Whenever THEY die, everything works fine.
I'm 99.9% sure it's because I have **FEATHER FALL**. I once swapped my feather fall piece and died, and the errors wouldn't show up.

Note: my friends still see feather effects on my character even after I unequip the item. Goes away at relog, but I'm the host.
Note 2: since I'm the host, my friends are lag-free when I die.

Error: 

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ZNetScene.RemoveObjects (System.Collections.Generic.List1[T] currentNearObjects, System.Collections.Generic.List1[T] currentDistantObjects) (at <cdb5bbec33f94182b860ca208c683122>:0)
ZNetScene.CreateDestroyObjects () (at <cdb5bbec33f94182b860ca208c683122>:0)
ZNetScene.Update () (at <cdb5bbec33f94182b860ca208c683122>:0)

**Comment by Eltharien** [comment]
@xilenasu My friend and I had the same issues for several months and after hours of troubleshooting i can say with 100% that it is the featherfall buff. I ended up dropping the pants that had the buff on the ground and doing a removedrops in the console to nuke them.
After that we both logged out and modified the config file so that the featherfall buff couldnt roll (just have to change a true false modifier in the file.

With mistlands on the way however this may become a moot point. I suspect Randy may be removing feather fall as an option as there is now an in game cloak that can have that buff as a native stat on it. If you are still playing pre-mistlands then you can search for the drop modifier in the config and disable it.

**Comment by xilenasu** [comment]
@Eltharien you were right about the Mistlands part. Featherfall was [updated](https://github.com/RandyKnapp/ValheimMods/blob/main/EpicLoot/patchnotes.md) to use vanilla effect. I guess the problem is solved.
