### ISSUE TITLE
Dual Wield Incompatability

### ISSUE THREAD

**Issue by ijks2** [RandyKnapp/ValheimMods#446]
Dual Wield 1.0.5 is incompatible with Epic Loot and breaks the game [for me atleast]

**Comment by SDUBZ** [comment]
i found its incompat with a few from same devs projects
[Error : BepInEx] Could not load [Cooking 1.1.11] because it is incompatible with: randyknapp.mods.extendeditemdataframework
[Error : BepInEx] Could not load [Dual Wield 1.0.5] because it is incompatible with: randyknapp.mods.epicloot
[Error : BepInEx] Could not load [Vitality 1.1.0] because it is incompatible with: randyknapp.mods.epicloot
just thought i would mention since they probably same related issues happening

**Comment by Vapok** [comment]
This has been resolved in 0.9.4

**Comment by SDUBZ** [comment]
any idea when the update will be published to public ? nexus or
thunderstore

**Comment by Vapok** [comment]
@SDUBZ We are working on that now actually.  Soon (TM)
