### ISSUE TITLE
[Epic Loot] How to translate "Rarity:" and "Effects:"

### ISSUE THREAD

**Issue by yxzwym** [RandyKnapp/ValheimMods#681]
![2](https://github.com/RandyKnapp/ValheimMods/assets/68624884/640b0200-f1cb-4b1a-869e-aaa0a2597420)

I can't find these two fields in translations.json

**Comment by RandyKnapp** [comment]
This looks like a legit bug and those fields were missed in the tooltip.
Thanks for the report

**Comment by jneb802** [comment]
Thanks for reporting. This is fixed in PR: https://github.com/OrianaVenture/Randy_Vapok_ValheimMods/pull/10

Specifically commit: https://github.com/OrianaVenture/Randy_Vapok_ValheimMods/pull/10/commits/a581d0650759929cd4afa0642d89320c8d595326

Two new localization strings will be added to translations.json file.
