### ISSUE TITLE
[Equipement QuickSlot] items "doubling" and food not stacking in hotkeys

### ISSUE THREAD

**Issue by sergeayotte** [RandyKnapp/ValheimMods#81]
After installing you newer version I created a new viking and, because of the way I play, he died, so I logout, remove him, create a new one, and a new world, and started the game.
First thing I noticed was that I found myself with some extra items, 2 torches and 1 tunic.
 
I started to noticed that food I collected and had in my hotkeys, did not add themselves in the hotkeys locations.
 
A played a while longer, before quitting the game, and restarting.
Even at restart, same behaviour on picking up berries or mushroom

Removed everything from hotbar, quit, renamed the config, restarted.
While writing the above, I noticed in the terminal windows that’s the mod I have says 2.0.2, although I downloaded this morning
 
Even after restarting with a fresh cfg, same behaviour.

List mods installed:
BepInEX 5.4.8
Equipment and Quick Slots 2.0.3 (see note regarding version)
BetterUI 1.6.1
TimeMod 0.6.0
FarmGrid 0.2.0
Craft Built Smel Cook Fuel Pull From Containers 1.9.0
Sleep 0.1.1
Locator 1.0.8
Skip Intro 1.0.0

Thanks for your GREAT work Randy!
Serge Ayotte

**Comment by KalenFrae** [comment]
Going to add this since it seems to be related

After installing v2.0 of quickslots (and up) all crafting and fuel adds use double the resources.  Seems to be a conflict with crafting from containers.  The doubling only happens if both are installed.  Did not happen prior to v2.0 of quickslots.

Posting for informational purposes only.

Thanks for all your work, really enjoy your mods
