### ISSUE TITLE
update 1.0.5 manifest?

### ISSUE THREAD

**Issue by Nchi** [RandyKnapp/ValheimMods#82]
```
{
  "ManifestVersion": 2,
  "AuthorName": "RandyKnapp",
  "Name": "RandyKnapp-EquipmentAndQuickSlots",
  "DisplayName": "EquipmentAndQuickSlots",
  "Version": "1.0.5",
  "Licence": "",
  "WebsiteURL": "https://valheim.thunderstore.io/package/RandyKnapp/EquipmentAndQuickSlots/",
  "Description": "Give equipped items their own dedicated inventory slots, plus three more hotkeyable quick slots.",
  "GameVersion": "N/A",
  "Dependencies": [],
  "OptionalDependencies": [],
  "Incompatibilities": [],
  "NetworkMode": "both",
  "PackageType": "mod",
  "InstallMode": "managed",
  "Loaders": [
        "bepinex"
    ],
  "ExtraData": {}
}
```

worked

**Comment by RandyKnapp** [comment]
What is the issue?

**Comment by Nchi** [comment]
importing the zip on r2modman fails with error "manifest is not version 2", IDK if this would also fix the install hotlink not working for 1.0.5 either which failed with "Mod does not exist
Unable to resolve ror2mm:- to a suitable Thunderstore mod"

**Comment by RandyKnapp** [comment]
I don't know what's wrong. Just remove it and get the latest version, which is 2.0.3

**Comment by JourneyOver** [comment]
Seems that he is trying to import the mod into r2modman (r2modman import only accepts manifest version 2, while normal install methods accept current implementation of the manifest (which is the way he should actually be installing this)) instead of going the route of installing the mod either through the "install with mod manager" button on thunderstore or going into the "online" section of r2modmanager and installing from there.
