### ISSUE TITLE
ImprovedBuildHud not working

### ISSUE THREAD

**Issue by bmreed78** [RandyKnapp/ValheimMods#93]
Mod seems to have no functionality - does not show any hud changes when building.
Installed using r2modman v3.1.9

Only loaded mods, in order, are:
BepInExPack_Valheim v5.4.900
EquipmentAndQuickSlots v2.0.4
ImprovedBuildHud v1.0.2
ItsJustWood v1.0.1
MinimalStatusEffect v1.0.3
SkipIntro v1.0.1 by purpledxd

All other mods seem to be functioning normally.

**Comment by bmreed78** [comment]
Forgot to mention, Valheim game version is 0.148.6

**Comment by lbrick** [comment]
@RandyKnapp I believe the issue is the following from the log:

`[Info   :   BepInEx] Loading [Improved Build HUD 1.0.1]
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'CraftFromContainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()`

Rebuilding works.

**Comment by bmreed78** [comment]
I never installed Craft From Containers mod, not even to try it.  I did, however, have MultiCraft installed prior to running into issues with Improved Build Hud.  MultiCraft, by MaxiMods, has issues where it won't work sometimes.  Also, very interesting to note, that MultiCraft also modifies the  quantities of required materials on the build hud, so it might be an issue with that mod overwriting some part of your mod.

The trouble is, simply deactivating MultiCraft, as I did in the example, didn't fix the issue. I will try uninstalling it alltogether and re-trying your mod.

**Comment by lbrick** [comment]
@bmreed78 I was pasting my logs from when I installed from the r2mod manager from Thunderstore. It was more to help our guy Randy out with bug finding.

The r2mod Manager says its 1.0.2 installed for the ImprovedBuildHud but when starting Valheim the BepInEx logs says 1.0.1

**Comment by bmreed78** [comment]
Thanks for the clarification.  After you posted it, I reinstalled
ImprovedBuildHud myself and guess what? got the same message in my log.
